use triple;

CREATE TABLE event (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    type VARCHAR(10) NOT NULL DEFAULT 'REVIEW',
    reviewId VARCHAR(36) NOT NULL,
    userId VARCHAR(36) NOT NULL,
    placeId VARCHAR(36) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT UQ_reviewId_1 UNIQUE (reviewId)
);

CREATE INDEX IDX_event_reviewId_1 ON event (reviewId);

CREATE TABLE review (
    id VARCHAR(36) NOT NULL,
    userId VARCHAR(36) NOT NULL,
    placeId VARCHAR(36) NOT NULL,
    content TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX IDX_review_placeId_1 ON review (placeId);

CREATE INDEX IDX_review_placeId_createdAt_1 ON review (placeId, createdAt);

CREATE TABLE photo (
    id VARCHAR(36) NOT NULL,
    reviewId VARCHAR(36) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT FK_review_photo_1 FOREIGN KEY (reviewId) REFERENCES review (id) ON DELETE CASCADE
);

CREATE TABLE mileage (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    userId VARCHAR(36) NOT NULL,
    point INT UNSIGNED NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT UQ_mileage_userId_1 UNIQUE (userId)
);

CREATE TABLE mileage_history (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    mileageId INT UNSIGNED NOT NULL,
    reviewId VARCHAR(36) NOT NULL,
    type VARCHAR(10) NOT NULL,
    point INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT FK_mileage_history_mileage_1 FOREIGN KEY (mileageId) REFERENCES mileage (id)
);

CREATE INDEX IDX_mileage_history_mileageId_createdAt_1 ON mileage_history (mileageId, createdAt);