POST http://localhost:3000/event
Content-Type: application/json

{
  "type": "REVIEW",
  "action": "MOD",
  "reviewId": "240a0658-dc5f-4878-9381-ebb7b2667772",
  "content": "좋아요!",
  "attachedPhotoIds": ["e4d1a64e-a531-46de-88d0-ff0ed70c0bb8", "e4d1a64e-a531-46de-88d0-ff0ed70c0bb7"],
  "userId":  "3ede0ef2-92b7-4817-a5f3-0c575361f745",
  "placeId": "2e4baf1c-5acb-4efb-a1af-eddada31b00f"
}