POST http://localhost:3000/events
Content-Type: application/json

{
  "type": "REVIEW",
  "action": "ADD",
  "reviewId": "340a0658-dc5f-4878-9381-ebb7b2667773",
  "content": "좋아요!",
  "attachedPhotoIds": [],
  "userId":  "3ede0ef2-92b7-4817-a5f3-0c575361f745",
  "placeId": "2e4baf1c-5acb-4efb-a1af-eddada31b00f"
}